services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=eventdb
      - MYSQL_ROOT_PASSWORD=example
    ports: ['3306:3306']
  redis:
    image: redis:7-alpine
    ports: ['6379:6379']
  rabbitmq:
    image: rabbitmq:3-management
    ports: ['5672:5672','15672:15672']
  app:
    build: .
    depends_on: [mysql, redis, rabbitmq]
    ports: ['8080:8080']
